In [1]:
import pandas as pd

In [2]:
# Python List

In [3]:
data = [
    ["Alice",25],
    ["Bob",45],
    ["Charlie",45]
]
#df = pd.DataFrame(data)
ds = pd.DataFrame(data,columns=["Name","Age"])
print(ds)

      Name  Age
0    Alice   25
1      Bob   45
2  Charlie   45

In [4]:
# Dictionary Lists

In [5]:
data = {
    "Name":["Alice","Bob","Charlie"],
    "Marks":[98,78,67]
}

dfs = pd.DataFrame(data)
print(dfs)

      Name  Marks
0    Alice     98
1      Bob     78
2  Charlie     67

In [ ]:
# JSON READ

In [8]:
df = pd.read_json("https://api.github.com/users/hadley/orgs")
print(df)

               login        id                           node_id  \
0              ggobi    423638  MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==
1            rstudio    513560  MDEyOk9yZ2FuaXphdGlvbjUxMzU2MA==
2             rstats    722735  MDEyOk9yZ2FuaXphdGlvbjcyMjczNQ==
3           ropensci   1200269  MDEyOk9yZ2FuaXphdGlvbjEyMDAyNjk=
4           rjournal   3330561  MDEyOk9yZ2FuaXphdGlvbjMzMzA1NjE=
5              r-dbi   5695665  MDEyOk9yZ2FuaXphdGlvbjU2OTU2NjU=
6        RConsortium  15366137  MDEyOk9yZ2FuaXphdGlvbjE1MzY2MTM3
7          tidyverse  22032646  MDEyOk9yZ2FuaXphdGlvbjIyMDMyNjQ2
8              r-lib  22618716  MDEyOk9yZ2FuaXphdGlvbjIyNjE4NzE2
9  rstudio-education  34165516  MDEyOk9yZ2FuaXphdGlvbjM0MTY1NTE2

                                             url  \
0              https://api.github.com/orgs/ggobi
1            https://api.github.com/orgs/rstudio
2             https://api.github.com/orgs/rstats
3           https://api.github.com/orgs/ropensci
4           https://api.github.com/orgs/rjournal
5              https://api.github.com/orgs/r-dbi
6        https://api.github.com/orgs/RConsortium
7          https://api.github.com/orgs/tidyverse
8              https://api.github.com/orgs/r-lib
9  https://api.github.com/orgs/rstudio-education

                                           repos_url  \
0            https://api.github.com/orgs/ggobi/repos
1          https://api.github.com/orgs/rstudio/repos
2           https://api.github.com/orgs/rstats/repos
3         https://api.github.com/orgs/ropensci/repos
4         https://api.github.com/orgs/rjournal/repos
5            https://api.github.com/orgs/r-dbi/repos
6      https://api.github.com/orgs/RConsortium/repos
7        https://api.github.com/orgs/tidyverse/repos
8            https://api.github.com/orgs/r-lib/repos
9  https://api.github.com/orgs/rstudio-education/...

                                          events_url  \
0           https://api.github.com/orgs/ggobi/events
1         https://api.github.com/orgs/rstudio/events
2          https://api.github.com/orgs/rstats/events
3        https://api.github.com/orgs/ropensci/events
4        https://api.github.com/orgs/rjournal/events
5           https://api.github.com/orgs/r-dbi/events
6     https://api.github.com/orgs/RConsortium/events
7       https://api.github.com/orgs/tidyverse/events
8           https://api.github.com/orgs/r-lib/events
9  https://api.github.com/orgs/rstudio-education/...

                                           hooks_url  \
0            https://api.github.com/orgs/ggobi/hooks
1          https://api.github.com/orgs/rstudio/hooks
2           https://api.github.com/orgs/rstats/hooks
3         https://api.github.com/orgs/ropensci/hooks
4         https://api.github.com/orgs/rjournal/hooks
5            https://api.github.com/orgs/r-dbi/hooks
6      https://api.github.com/orgs/RConsortium/hooks
7        https://api.github.com/orgs/tidyverse/hooks
8            https://api.github.com/orgs/r-lib/hooks
9  https://api.github.com/orgs/rstudio-education/...

                                          issues_url  \
0           https://api.github.com/orgs/ggobi/issues
1         https://api.github.com/orgs/rstudio/issues
2          https://api.github.com/orgs/rstats/issues
3        https://api.github.com/orgs/ropensci/issues
4        https://api.github.com/orgs/rjournal/issues
5           https://api.github.com/orgs/r-dbi/issues
6     https://api.github.com/orgs/RConsortium/issues
7       https://api.github.com/orgs/tidyverse/issues
8           https://api.github.com/orgs/r-lib/issues
9  https://api.github.com/orgs/rstudio-education/...

                                         members_url  \
0  https://api.github.com/orgs/ggobi/members{/mem...
1  https://api.github.com/orgs/rstudio/members{/m...
2  https://api.github.com/orgs/rstats/members{/me...
3  https://api.github.com/orgs/ropensci/members{/...
4  https://api.github.com/orgs/rjournal/members{/...
5  https://api.github.com/orgs/r-dbi/members{/mem...
6  https://api.github.com/orgs/RConsortium/member...
7  https://api.github.com/orgs/tidyverse/members{...
8  https://api.github.com/orgs/r-lib/members{/mem...
9  https://api.github.com/orgs/rstudio-education/...

                                  public_members_url  \
0  https://api.github.com/orgs/ggobi/public_membe...
1  https://api.github.com/orgs/rstudio/public_mem...
2  https://api.github.com/orgs/rstats/public_memb...
3  https://api.github.com/orgs/ropensci/public_me...
4  https://api.github.com/orgs/rjournal/public_me...
5  https://api.github.com/orgs/r-dbi/public_membe...
6  https://api.github.com/orgs/RConsortium/public...
7  https://api.github.com/orgs/tidyverse/public_m...
8  https://api.github.com/orgs/r-lib/public_membe...
9  https://api.github.com/orgs/rstudio-education/...

                                          avatar_url  \
0  https://avatars.githubusercontent.com/u/423638...
1  https://avatars.githubusercontent.com/u/513560...
2  https://avatars.githubusercontent.com/u/722735...
3  https://avatars.githubusercontent.com/u/120026...
4  https://avatars.githubusercontent.com/u/333056...
5  https://avatars.githubusercontent.com/u/569566...
6  https://avatars.githubusercontent.com/u/153661...
7  https://avatars.githubusercontent.com/u/220326...
8  https://avatars.githubusercontent.com/u/226187...
9  https://avatars.githubusercontent.com/u/341655...

                                         description
0
1
2                                                NaN
3              Tools and R Packages for Open Science
4                                                NaN
5                                      R + databases
6  The R Consortium, Inc was established to provi...
7  The tidyverse is a collection of R packages th...
8
9

In [ ]:
# Numpy

### array = ([1,2],[3,4])
ds = pd.DataFrame(array,columns=("A","B"))
print(ds)

In [ ]:
# CSV

In [17]:
fd = pd.read_csv("https://raw.githubusercontent.com/CourseMaterial/DataWrangling/main/flowerdataset.csv")
print(fd)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [18]:
fd.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [19]:
fd.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.9 KB

In [20]:
fd.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000