In [2]:
import pandas as pd

In [7]:
url = "movies.csv"
df = pd.read_csv(url)
df.head()

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
0,3f297cf0-2e9d-31c0-b566-6676dd8548b2,Titanic,1997,https://www.rottentomatoes.com/m/titanic,1,88%,69%
1,ed95f56a-dc82-3197-97fd-763ab02d032a,Contagion,2011,https://www.rottentomatoes.com/m/contagion_2011,2,85%,63%
2,f639ff01-58ec-3847-95a0-c1b1b8de5550,Deepwater Horizon,2016,https://www.rottentomatoes.com/m/deepwater_hor...,3,82%,82%
3,7712badd-e5ec-3d28-8787-7fd6301f5a0a,The Wave,2015,https://www.rottentomatoes.com/m/the_wave_2016,4,83%,66%
4,65abd2ca-6095-3acc-b072-00443c4c1fb5,The Impossible,2012,https://www.rottentomatoes.com/m/the_impossibl...,5,82%,84%

In [6]:
best = df.query("movieYear > 2000 and critic_score > '80%'")
best

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
1,ed95f56a-dc82-3197-97fd-763ab02d032a,Contagion,2011,https://www.rottentomatoes.com/m/contagion_2011,2,85%,63%
2,f639ff01-58ec-3847-95a0-c1b1b8de5550,Deepwater Horizon,2016,https://www.rottentomatoes.com/m/deepwater_hor...,3,82%,82%
3,7712badd-e5ec-3d28-8787-7fd6301f5a0a,The Wave,2015,https://www.rottentomatoes.com/m/the_wave_2016,4,83%,66%
4,65abd2ca-6095-3acc-b072-00443c4c1fb5,The Impossible,2012,https://www.rottentomatoes.com/m/the_impossibl...,5,82%,84%
5,5cf3dfaa-1396-3c86-85ec-3173cad39f22,Black Sea,2014,https://www.rottentomatoes.com/m/black_sea,6,81%,58%

In [8]:
df.query("movieTitle == 'The Wave'")

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
3,7712badd-e5ec-3d28-8787-7fd6301f5a0a,The Wave,2015,https://www.rottentomatoes.com/m/the_wave_2016,4,83%,66%

In [9]:
df

,movieId,movieTitle,movieYear,movieURL,movieRank,critic_score,audience_score
0,3f297cf0-2e9d-31c0-b566-6676dd8548b2,Titanic,1997,https://www.rottentomatoes.com/m/titanic,1,88%,69%
1,ed95f56a-dc82-3197-97fd-763ab02d032a,Contagion,2011,https://www.rottentomatoes.com/m/contagion_2011,2,85%,63%
2,f639ff01-58ec-3847-95a0-c1b1b8de5550,Deepwater Horizon,2016,https://www.rottentomatoes.com/m/deepwater_hor...,3,82%,82%
3,7712badd-e5ec-3d28-8787-7fd6301f5a0a,The Wave,2015,https://www.rottentomatoes.com/m/the_wave_2016,4,83%,66%
4,65abd2ca-6095-3acc-b072-00443c4c1fb5,The Impossible,2012,https://www.rottentomatoes.com/m/the_impossibl...,5,82%,84%
5,5cf3dfaa-1396-3c86-85ec-3173cad39f22,Black Sea,2014,https://www.rottentomatoes.com/m/black_sea,6,81%,58%
6,c4b30fa1-9036-3c88-a8b1-2731bf3afc38,Greenland,2020,https://www.rottentomatoes.com/m/greenland,7,78%,63%
7,d1e52d53-1447-337e-8e14-d20f8a856093,The Poseidon Adventure,1972,https://www.rottentomatoes.com/m/1016584-posei...,8,80%,76%
8,4f1acbb5-6c09-330a-87b9-530a698c5e65,Sharknado,2013,https://www.rottentomatoes.com/m/sharknado,9,77%,34%
9,2645a114-3f86-3f6e-8da1-74f0804df941,Airport,1970,https://www.rottentomatoes.com/m/airport,10,75%,54%
10,e9132f51-8de9-3e1f-b390-699bce9cde57,The Towering Inferno,1974,https://www.rottentomatoes.com/m/towering_inferno,11,68%,72%
11,d3d3c30b-9116-3d4b-978b-1a9196e35309,The Burning Sea,2021,https://www.rottentomatoes.com/m/the_burning_sea,12,73%,61%
12,6898bf3d-32d5-3ac6-aab4-f202d4fe56ba,Snakes on a Plane,2006,https://www.rottentomatoes.com/m/snakes_on_a_p...,13,69%,49%
13,4a07a9a5-846c-309d-9c59-792757fda630,Twister,1996,https://www.rottentomatoes.com/m/1071167-twister,14,63%,58%
14,3a886fc1-2e8f-37a5-9687-29e0e2e89e72,Sharknado 2: The Second One,2014,https://www.rottentomatoes.com/m/sharknado_2_t...,15,61%,32%
15,a9989888-e0d4-38cc-981f-be80a7bd59b8,The Last Voyage,1960,https://www.rottentomatoes.com/m/last_voyage,16,60%,58%
16,b7ecb431-d281-3ece-ac8a-fd716d125c91,Don't Look Up,2021,https://www.rottentomatoes.com/m/dont_look_up_...,17,56%,78%
17,ca6dc186-e11b-344c-8de9-33f0516ba0a5,Volcano,1997,https://www.rottentomatoes.com/m/1076267-volcano,18,49%,32%
18,c87b1266-de76-324a-8893-d85dc2069127,San Andreas,2015,https://www.rottentomatoes.com/m/san_andreas,19,49%,52%
19,336bc05b-8e3b-35d2-b100-d19442076102,The 33,2015,https://www.rottentomatoes.com/m/the_33,20,48%,59%
20,73b3369d-11dd-3b3f-b6b9-ea8fcbbd3cc6,Earthquake,1974,https://www.rottentomatoes.com/m/earthquake,21,44%,36%
21,97a1f7a6-3409-38db-a572-4494dd457cf2,The Perfect Storm,2000,https://www.rottentomatoes.com/m/perfect_storm,22,46%,63%
22,9ec46d89-f20b-3fc1-b1a7-42731405c0ce,The Hurricane Heist,2018,https://www.rottentomatoes.com/m/the_hurricane...,23,47%,23%
23,f72c54d2-aab0-3826-83ff-6219dd376201,The Day After Tomorrow,2004,https://www.rottentomatoes.com/m/day_after_tom...,24,45%,50%
24,99476c7a-ee42-30c8-b809-50feefdaca08,Deep Impact,1998,https://www.rottentomatoes.com/m/deep_impact,25,45%,43%
25,0121b88c-4911-39fe-9b6b-99c38ef7d2c3,The Core,2003,https://www.rottentomatoes.com/m/core,26,39%,34%
26,3a37c242-36c8-370f-b9e6-c3904c8e9f3d,The High and the Mighty,1954,https://www.rottentomatoes.com/m/high_and_the_...,27,46%,59%
27,843f9ea8-c0ff-3271-8f50-2d23e88623ae,2012,2009,https://www.rottentomatoes.com/m/2012,28,39%,47%
28,69b74cdd-8d1f-3d76-9911-081068ea307e,Moonfall,2022,https://www.rottentomatoes.com/m/moonfall,29,35%,70%
29,ddafc1e8-42d9-3d6b-bf70-ccda3b9f3884,Armageddon,1998,https://www.rottentomatoes.com/m/armageddon,30,43%,73%
30,be13315a-005a-3323-a896-5d31d03238fc,Raise the Titanic,1980,https://www.rottentomatoes.com/m/raise_the_tit...,31,38%,28%
31,b3bdd8d9-bf20-3ac5-af45-75106b50ea7b,Hurricane,1979,https://www.rottentomatoes.com/m/1010240-hurri...,32,33%,44%
32,c6e9b4dc-a79d-39b3-a780-3e49df624f81,Sharknado 3: Oh Hell No!,2015,https://www.rottentomatoes.com/m/sharknado_3_o...,33,36%,28%
33,1f8e1c28-d0ef-38e8-9e5d-2c20727e4c2a,The Hindenburg,1975,https://www.rottentomatoes.com/m/1009649-hinde...,34,31%,39%
34,30866057-f1b7-37dc-ada8-5662ce260f63,Poseidon,2006,https://www.rottentomatoes.com/m/poseidon,35,33%,43%
35,96a45e7e-7687-3606-b100-516e27699536,Airport '77,1977,https://www.rottentomatoes.com/m/airport_77,36,40%,32%
36,3bff08f7-beea-3140-809e-44998868ed85,Hard Rain,1998,https://www.rottentomatoes.com/m/hard_rain,37,34%,34%
37,aa163990-7bca-35fd-82c9-356372cfea5d,Sharknado 5: Global Swarming,2017,https://www.rottentomatoes.com/m/sharknado_5_g...,38,30%,37%
38,e82ba7ff-39ff-3ee5-bd0c-8cb57b171685,The Cassandra Crossing,1977,https://www.rottentomatoes.com/m/the_cassandra...,39,36%,52%
39,921c17f7-cb06-3fe4-ba97-8ba45c7fe540,Airport 1975,1974,https://www.rottentomatoes.com/m/airport_1975,40,30%,38%
40,bca94c43-77aa-3433-a626-8e5655daa85a,Dante's Peak,1997,https://www.rottentomatoes.com/m/dantes_peak,41,28%,38%
41,b8f79486-73fc-3f56-ae2c-2efc34114cb8,Pompeii,2014,https://www.rottentomatoes.com/m/pompeii_2013,42,27%,34%
42,ae632ee7-1a5f-30f9-aecb-fb5cfd5d5a2b,The Last Sharknado: It's About Time,2018,https://www.rottentomatoes.com/m/the_last_shar...,43,27%,37%
43,224d8fb5-d8d5-3048-b164-07e64ba92a81,Daylight,1996,https://www.rottentomatoes.com/m/daylight,44,26%,37%
44,07d1597e-156c-3130-9552-c3d908cc5183,Into the Storm,2014,https://www.rottentomatoes.com/m/into_the_stor...,45,21%,41%
45,bc0d6132-eda5-3209-8fc2-b7e1fb082700,Geostorm,2017,https://www.rottentomatoes.com/m/geostorm,46,18%,35%
46,16028c9f-b7c9-30c0-a0c1-5fee56b7cbf1,Sharknado: The 4th Awakens,2016,https://www.rottentomatoes.com/m/sharknado_the...,47,14%,25%
47,6af0ed89-e2ab-3fe0-a8a1-668a698dd7eb,The Concorde: Airport '79,1979,https://www.rottentomatoes.com/m/the_concorde_...,48,25%,14%
48,efb3cf40-69f9-33bf-ae1b-264bc6e9f7ee,Meteor,1979,https://www.rottentomatoes.com/m/1013772-meteor,49,5%,14%
49,e9489cb8-c34e-3be7-ba47-411afbb7d539,Beyond the Poseidon Adventure,1979,https://www.rottentomatoes.com/m/beyond_the_po...,50,0%,21%