In [2]:
import pandas as pd

In [4]:
url = "synthetic_dataset.csv"
df = pd.read_csv(url)
df

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

[4362 rows x 5 columns]

In [6]:
df_2 = df.iloc[0:11]
df_2

   Category   Price    Rating         Stock  Discount
0       NaN  5548.0  1.870322           NaN       0.0
1       NaN  3045.0  4.757798           NaN      38.0
2       NaN  4004.0       NaN      In Stock       0.0
3       NaN  4808.0  1.492085           NaN      33.0
4       NaN  1817.0       NaN  Out of Stock      23.0
5       NaN  3522.0       NaN           NaN       NaN
6         C   667.0  3.668341      In Stock      41.0
7         A  7125.0  4.983998  Out of Stock       7.0
8         A  2777.0  2.678384      In Stock       6.0
9       NaN   463.0  4.626187           NaN       3.0
10        A  1151.0  2.947838           NaN       NaN